### ISSUE TITLE
Missing Component

### ISSUE THREAD

**Issue by PHommers** [samskolli/Pegasus#1]
Hi Sam,
thank you for your work. Any chance you're doing another sort component? I've tried and I'm afraid I'm stuck.

**Comment by samskolli** [comment]
Sure ... give me a few days.

**Comment by samskolli** [comment]
PHommers, I have added the Sort component. Take a look at the SortExample.cs file in the Pegasus.Demo project. Should be pretty straight forward.

**Comment by samskolli** [comment]
Let me know, so I can close this issue.
