### ISSUE TITLE
Inconsistent assembly references

### ISSUE THREAD

**Issue by zafstojano** [samskolli/Pegasus#2]
I just downloaded the code and when I run Program.cs from Pegasus.Demo, I stumble upon these 2 errors:

`Assembly 'Microsoft.SqlServer.ScriptTask' with identity 'Microsoft.SqlServer.ScriptTask, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' uses 'Microsoft.SqlServer.ManagedDTS, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' which has a higher version than referenced assembly 'Microsoft.SqlServer.ManagedDTS' with identity 'Microsoft.SqlServer.ManagedDTS, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
`
And this one too:
`Assembly 'Microsoft.SqlServer.SQLTask' with identity 'Microsoft.SqlServer.SQLTask, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' uses 'Microsoft.SqlServer.ManagedDTS, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' which has a higher version than referenced assembly 'Microsoft.SqlServer.ManagedDTS' with identity 'Microsoft.SqlServer.ManagedDTS, Version=12.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'`

How do I solve this? Thanks in advance.

**Comment by samskolli** [comment]
Check SQL Server versions. This library was built with 2016.
